[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
board_build.partitions = huge_app.csv
board_build.f_cpu = 240000000L

monitor_speed = 115200
upload_speed = 921600

; TFLite Micro is in lib/tfmicro (cloned from GitHub)
; MAVLink c_library_v2 is in lib/mavlink

; Use PSRAM for TFLite arena
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -O2
