"""Export trained model to int8 TFLite and C header for ESP32.

Usage:
    python export_model.py
"""

import numpy as np
from pathlib import Path
from PIL import Image
import tensorflow as tf

import config


def load_representative_dataset():
    """Load a subset of training images for quantization calibration."""
    images = []

    for class_name in config.CLASS_NAMES:
        class_dir = config.DATA_DIR / class_name
        if not class_dir.exists():
            continue

        for img_path in sorted(class_dir.iterdir()):
            if img_path.suffix.lower() not in ('.jpg', '.jpeg', '.png', '.bmp'):
                continue

            img = Image.open(img_path).convert('L')
            w, h = img.size

            crop_h = int(h * (1.0 - config.CROP_BOTTOM_PCT))
            img = img.crop((0, 0, w, crop_h))
            img = img.resize((config.IMG_WIDTH, config.IMG_HEIGHT), Image.BILINEAR)

            arr = np.array(img, dtype=np.float32) / 255.0
            images.append(arr)

    images = np.array(images)[..., np.newaxis]  # (N, H, W, 1)
    print(f"Representative dataset: {len(images)} images")
    return images


def representative_data_gen(images):
    """Generator for TFLite quantization calibration."""
    def gen():
        for img in images:
            yield [img[np.newaxis, ...]]  # batch of 1
    return gen


def convert_to_tflite(model, rep_images):
    """Convert Keras model to int8 quantized TFLite."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # Full integer quantization
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_data_gen(rep_images)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    return tflite_model


def export_c_header(tflite_data, output_path):
    """Export TFLite model as C header file."""
    with open(output_path, 'w') as f:
        f.write('#pragma once\n\n')
        f.write('// Auto-generated by export_model.py — do not edit manually\n')
        f.write(f'// Model size: {len(tflite_data)} bytes\n\n')
        f.write('#include <stdint.h>\n\n')
        f.write('alignas(16) const unsigned char g_model_data[] = {\n')

        for i in range(0, len(tflite_data), 12):
            chunk = tflite_data[i:i+12]
            hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f'    {hex_str},\n')

        f.write('};\n\n')
        f.write(f'const unsigned int g_model_data_len = {len(tflite_data)};\n')


def main():
    config.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Load best model
    model_path = config.MODELS_DIR / "best_model.keras"
    if not model_path.exists():
        print(f"Model not found: {model_path}")
        print("Run train.py first!")
        return

    print(f"Loading model from {model_path}")
    model = tf.keras.models.load_model(str(model_path))

    # Load representative dataset
    rep_images = load_representative_dataset()

    # Convert to int8 TFLite
    print("Converting to int8 TFLite...")
    tflite_data = convert_to_tflite(model, rep_images)

    # Save TFLite
    config.TFLITE_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(config.TFLITE_MODEL_PATH, 'wb') as f:
        f.write(tflite_data)
    print(f"TFLite model saved: {config.TFLITE_MODEL_PATH} ({len(tflite_data)} bytes)")

    # Export C header
    config.C_HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    export_c_header(tflite_data, config.C_HEADER_PATH)
    print(f"C header saved: {config.C_HEADER_PATH}")

    # Verify TFLite model
    print("\nVerifying TFLite model...")
    interpreter = tf.lite.Interpreter(model_content=tflite_data)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    print(f"Input:  {input_details[0]['shape']} dtype={input_details[0]['dtype']}")
    print(f"Output: {output_details[0]['shape']} dtype={output_details[0]['dtype']}")
    print(f"Input  quant: scale={input_details[0]['quantization'][0]:.6f}, "
          f"zero_point={input_details[0]['quantization'][1]}")
    print(f"Output quant: scale={output_details[0]['quantization'][0]:.6f}, "
          f"zero_point={output_details[0]['quantization'][1]}")

    # Quick test with one image
    test_img = rep_images[0:1].copy()
    # Quantize input
    input_scale = input_details[0]['quantization'][0]
    input_zp = input_details[0]['quantization'][1]
    test_input = np.round(test_img / input_scale + input_zp).astype(np.int8)

    interpreter.set_tensor(input_details[0]['index'], test_input)
    interpreter.invoke()

    output = interpreter.get_tensor(output_details[0]['index'])
    output_scale = output_details[0]['quantization'][0]
    output_zp = output_details[0]['quantization'][1]
    dequant = (output.astype(np.float32) - output_zp) * output_scale
    pred = np.argmax(dequant)
    print(f"\nTest prediction: {config.CLASS_NAMES[pred]} (raw: {dequant})")

    print("\nExport complete!")


if __name__ == '__main__':
    main()
